
services:

  redis:
    image: redis:latest
    container_name: tikky_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - tikky

  backend:
    build:
      context: ./backend
    container_name: tikky_backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - tikky

networks:
  tikky:
    driver: bridge
